DELETE http://127.0.0.1:3308/project-media/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlX2lkIjoxLCJvcmdhbml6YXRpb25faWQiOjEsImlhdCI6MTc3MjY0MDkzNCwiZXhwIjoxNzcyNzI3MzM0LCJzdWIiOiIyIn0.ZO1h2zLRkXYCV931uDP1edkdKqQnfeWelsQ3rdnAR48

{
  "project_id": "2",
  "name": "Foto 2 do Aplicativo",
  "media": "https://br.freepik.com/fotos-gratis/pescador-segurando-o-peixe-na-mao-no-fundo-desfocado_3089673.htm#fromView=search&page=1&position=24&uuid=7160bb5e-141b-4c9f-8d89-6c5eca246868&query=fish"
}